# Base image
FROM redis
# author
MAINTAINER ruoyi

# Mount directory
VOLUME /home/ruoyi/redis
# Create directory
RUN mkdir -p /home/ruoyi/redis
# Specify path
WORKDIR /home/ruoyi/redis
# Copy conf file to path
COPY ./conf/redis.conf /home/ruoyi/redis/redis.conf
