# Base image
FROM  openjdk:8-jre
# author
MAINTAINER ruoyi

# Mount directory
VOLUME /home/ruoyi
# Create directory
RUN mkdir -p /home/ruoyi
# Specify path
WORKDIR /home/ruoyi
# Copy jar file to path
COPY ./jar/ruoyi-auth.jar /home/ruoyi/ruoyi-auth.jar
# Start authentication service
ENTRYPOINT ["java","-jar","ruoyi-auth.jar"]