# Base image
FROM  openjdk:8-jre
# author
MAINTAINER ruoyi

# Mount directory
VOLUME /home/ruoyi
# Create directory
RUN mkdir -p /home/ruoyi
# Specify path
WORKDIR /home/ruoyi
# Copy jar file to path
COPY ./jar/ruoyi-modules-file.jar /home/ruoyi/ruoyi-modules-file.jar
# Start file service
ENTRYPOINT ["java","-jar","ruoyi-modules-file.jar"]