# Base image
FROM nginx
# author
MAINTAINER ruoyi

# Mount directory
VOLUME /home/ruoyi/projects/ruoyi-ui
# Create directory
RUN mkdir -p /home/ruoyi/projects/ruoyi-ui
# Specify path
WORKDIR /home/ruoyi/projects/ruoyi-ui
# Copy conf file to path
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# Copy html files to path
COPY ./html/dist /home/ruoyi/projects/ruoyi-ui
