# Base image
FROM  openjdk:8-jre
# author
MAINTAINER ruoyi

# Mount directory
VOLUME /home/ruoyi
# Create directory
RUN mkdir -p /home/ruoyi
# Specify path
WORKDIR /home/ruoyi
# Copy jar file to path
COPY ./jar/ruoyi-gateway.jar /home/ruoyi/ruoyi-gateway.jar
# Start gateway service
ENTRYPOINT ["java","-jar","ruoyi-gateway.jar"]